version: '3.9'

services:
  postgres-db:
    container_name: postgres-database
    image: postgres:latest
    restart: always #reinicializa o container automaticamente independente do motivo que fez ele parar
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: petshop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak-auth-server:
    container_name: keycloak-auth-server
    image: quay.io/keycloak/keycloak:latest
    restart: always
    ports:
      - '8080:8080'
    command:
      - start-dev
    depends_on:
      - postgres-db
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-db:5432/petshop
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin

volumes:
  postgres-data: