name: Frontend CI/CD

on: workflow_dispatch

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd frontend-v2
          npm install

      - name: Build
        run: |
          cd frontend-v2
          npm run build